; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env_default]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = esptool
board_upload.flash_size = 8MB
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.events_core = 1
board_build.arduino_core = 1
board_build.erase_flash = true
board_build.partitions = huge_app.csv
build_type = release
monitor_speed = 115200
upload_speed = 921600
upload_port = 
build_flags = 
	-I include
	-DBOARD_HAS_PSRAM
	-O3

[env:WiFiProv]
extends = env_default
build_src_filter = +<WiFiProv>
build_flags = 
	${env_default.build_flags}
lib_archive = no
lib_deps = bblanchon/ArduinoJson@^7.4.2

[env:WiFiProv_SoftAP]
extends = env_default
build_src_filter = +<WiFiProv_SoftAP>
build_flags = 
	${env_default.build_flags}
lib_deps = bblanchon/ArduinoJson@^7.4.2

[env:WiFiProv_extLib_simple]
extends = env_default
build_src_filter = +<WiFiProv-extLib-simple>
build_flags = 
	${env_default.build_flags}
lib_deps = bblanchon/ArduinoJson@^7.4.2

[env:WiFiProv_extLib_advanced]
extends = env_default
build_src_filter = +<WiFiProv-extLib-advanced>
build_flags = 
	${env_default.build_flags}
lib_deps = bblanchon/ArduinoJson@^7.4.2

[env:WiFiProv_extLib_configuration]
extends = env_default
build_src_filter = +<WiFiProv-extLib-configuration>
build_flags = 
	${env_default.build_flags}
lib_deps = bblanchon/ArduinoJson@^7.4.2

[env:Specs]
extends = env_default
build_src_filter = +<ESP32_Specs_Reader>
upload_speed = 115200
lib_deps = bblanchon/ArduinoJson@^7.4.2
