; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env_default]
platform = espressif32 
board = esp32dev
framework = arduino

upload_protocol = esptool

; Board-specific configurations
board_upload.flash_size = 8MB     ; Temporarily changing to 8MB because I am using a different test board Set flash memory size to 16MB
board_build.f_cpu = 240000000L     ; Set CPU frequency to 240MHz
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.events_core = 1
board_build.arduino_core = 1
board_build.erase_flash = true

board_build.partitions = huge_app.csv   ; Allow bigger app size for BLE + WiFiProv

; Set build type to "release" for optimized code
build_type = release

; Serial monitor and upload speeds
monitor_speed = 115200       ; Set serial monitor baud rate
upload_speed = 921600        ; Set upload baud rate for faster flashing
upload_port = 

; Compiler optimization and board-specific flags
build_flags = 
    -I include
    -DBOARD_HAS_PSRAM  ; Define macro to enable PSRAM support
    -O3

[env:WiFiProv]
extends= env_default
build_src_filter=+<WiFiProv>
build_flags = 
    ${env_default.build_flags}
lib_archive = no

; NOTE: This line solves the issue: "E (3621) simple_ble: simple_ble_start enable controller failed 259<CR>"
; according to: https://github.com/espressif/arduino-esp32/issues/11181

; Optional: helps with BLE and WiFi provisioning examples

[env:WiFiProv_SoftAP]
extends= env_default
build_src_filter=+<WiFiProv_SoftAP>
build_flags = 
    ${env_default.build_flags}

[env:Specs]
extends = env_default
build_src_filter = +<ESP32_Specs_Reader>
; Lower upload speed for reliability during diagnostics
upload_speed = 115200
; Explicitly set upload_port here if known, e.g. COM5
; upload_port = COM5
; If actual flash is 8MB keep board_upload.flash_size at 8MB
; board_upload.flash_size = 8MB

